pipeline {

    agent {
        label "any"
    }
    //not needed

    //     environment {
    //             EXAMPLE_CREDS = credentials('example-credentials-id')
    //     }

 	stages {
        stage("clean artifacts") {
            steps {
                catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {

                     sh " rm -r /var/jenkins_home/workspace/devopsmakeeasy/artifact"
                   //sh " rm -r /var/jenkins_home/workspace/artifact"
                }
                }
        }

        stage('artifacts'){
          steps{
              sh "ls -ll"
              sh "pwd"
              sh "ls -ll /var/jenkins_home/workspace"
              sh "pwd"
              sh "ls"
              sh "mkdir /var/jenkins_home/workspace/artifact"
              sh "ls -ll /var/jenkins_home/workspace"
              sh "cp -r /var/jenkins_home/workspace/devopsmakeeasy/. /var/jenkins_home/workspace/artifact/  "
              sh "ls -la /var/jenkins_home/workspace/artifact"
              sh "mv /var/jenkins_home/workspace/artifact/ /var/jenkins_home/workspace/devopsmakeeasy/ "
              sh "ls -la /var/jenkins_home/workspace/devopsmakeeasy"
              sh "ls -ll /var/jenkins_home/workspace/devopsmakeeasy/artifact"
              sh "tar -zcvf artifact.tar.gz /var/jenkins_home/workspace/devopsmakeeasy/artifact "
              sh "ls -la /var/jenkins_home/workspace/devopsmakeeasy/"
              }
          }


        stage("publish to nexus") {
          steps {
             script {
               sh('curl -v -u admin:admin --upload-file artifact.tar.gz http://147.182.235.195:8081/repository/maven-nexus-repo/var/jenkins_home/workspace/devopsmakeeasy/artifact/artifact.tar.gz')

               }
          }
	  }

	   stage("clean artifacts tars") {
            steps {
                catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {

                    sh "rm /var/jenkins_home/workspace/devopsmakeeasy/artifact.tar.gz"
                    //sh "rm /var/jenkins_home/workspace/devopsmakeeasy/artifact/artifact.tar.gz"


                }
                }
        }

    stage('Deploy') {
	      steps{
	          script{
	              //sh "chmod +x /var/jenkins_home/workspace/devopsmakeeasy/artifact/artifact.tar.gz"
                  def remote = [:]
                remote.name = "143.110.180.23"
                remote.host = "143.110.180.23"
                remote.user = "root"
                remote.password = "uBbuntu@123Server"
                remote.allowAnyHosts = true
                //i want to run the script from server to node end

                    //writeFile file: 'srcipt_devops.sh', text: 'ls -lrt'
                   sshPut remote: remote, from: '/var/jenkins_home/workspace/devopsmakeeasy/srcipt_devops.sh', into: '/var/www/'
                    sshCommand remote: remote, command: "cd .. && cd var/www/ && chmod +x srcipt_devops.sh && ./srcipt_devops.sh"
                    sshCommand remote: remote, command: "cd .. && cd var/www/devopsmakeeasy.com/ && chmod +x srcipt_larabuild.sh && ./srcipt_larabuild.sh"



                  //sshCommand remote: remote, command: "cd .. && cd var/www/ && curl --create-dirs -O --output ../var/www/ http://157.245.255.2:8081/repository/maven-nexus-repo/var/jenkins_home/workspace/devopsmakeeasy/artifact/artifact.tar.gz && pwd && ls -la && tar -xvzf artifact.tar.gz && cd /var/www/var/jenkins_home/workspace/devopsmakeeasy/artifact && mv * /var/www/ "

              }
         }
      }
       stage("Build") {
            environment {
                DB_HOST = credentials("localhost")
                DB_DATABASE = credentials("nest")
                DB_USERNAME = credentials("pencil")
                DB_PASSWORD = credentials("123456")
            }
            steps {
                sh 'php --version'
                sh 'composer install'
                sh 'composer --version'
                sh 'cp .env.example .env'
                sh 'echo DB_HOST=${DB_HOST} >> .env'
                sh 'echo DB_USERNAME=${DB_USERNAME} >> .env'
                sh 'echo DB_DATABASE=${DB_DATABASE} >> .env'
                sh 'echo DB_PASSWORD=${DB_PASSWORD} >> .env'
                sh 'php artisan key:generate'
                sh 'cp .env .env.testing'
                sh 'php artisan migrate'
            }
        }
        stage("Unit test") {
            steps {
                sh 'php artisan test'
            }
        }
    }
}
